const {Document,Packer,Paragraph,TextRun,ImageRun,AlignmentType,PageOrientation,Table,TableRow,TableCell,WidthType,BorderStyle,UnderlineType}=require("docx");
const JSZip=require("jszip"),nodemailer=require("nodemailer");
const LOGO=Buffer.from("/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAA4KCw0LCQ4NDA0QDw4RFiQXFhQUFiwgIRokNC43NjMuMjI6QVNGOj1OPjIySGJJTlZYXV5dOEVmbWVabFNbXVn/2wBDAQ8QEBYTFioXFypZOzI7WVlZWVlZWVlZWVlZWVlZWVlZWVlZW","base64");
const P=t=>new Paragraph(t),R=t=>new TextRun(t),line=n=>"_".repeat(n),br=i=>{const[y,m,d]=String(i).split("-");return`${d}/${m}/${y}`},safe=s=>String(s).normalize("NFD").replace(/[\u0300-\u036f]/g,"");
function ext(i){const M=["JANEIRO","FEVEREIRO","MARÇO","ABRIL","MAIO","JUNHO","JULHO","AGOSTO","SETEMBRO","OUTUBRO","NOVEMBRO","DEZEMBRO"],[y,m,d]=String(i).split("-").map(Number);return`${String(d).padStart(2,"0")} de ${M[m-1]} de ${y}`}
function nw(n){n=Number(n);const u=["ZERO","UM","DOIS","TRÊS","QUATRO","CINCO","SEIS","SETE","OITO","NOVE"],e={10:"DEZ",11:"ONZE",12:"DOZE",13:"TREZE",14:"QUATORZE",15:"QUINZE",16:"DEZESSEIS",17:"DEZESSETE",18:"DEZOITO",19:"DEZENOVE"};if(n<10)return u[n];if(n<20)return e[n];if(n<100){const c=Math.floor(n/10)*10,t=n%10;return u[c/10]+"NTA"+(t?` E ${u[t]}`:"")}}
function head(){return[P({alignment:AlignmentType.CENTER,children:[new ImageRun({data:LOGO,transformation:{width:55,height:73},type:"jpg"})]}),P({alignment:AlignmentType.CENTER,children:[R({text:"HOSPITAL ALTA VIDA",bold:true,size:28})]}),P({alignment:AlignmentType.CENTER,children:[R({text:"CNPJ: 23.454.892/0001-00",size:18})]})]}
function med(s){let m=String(s||"").match(/^(.*?)-{3,}\s*(.+)$/);return m?{i:m[1].trim(),q:m[2].trim()}:{i:String(s||"").trim(),q:""}}
function atestado(d){let c=head();c.push(P({alignment:AlignmentType.CENTER,children:[R({text:"ATESTADO MÉDICO",bold:true,underline:{type:UnderlineType.SINGLE}})]}),P({text:""}),P({children:[R({text:`Paciente: ${d.paciente}`})]}),P({children:[R({text:`Data: ${ext(d.hoje)}`})]}));return new Document({sections:[{children:c}]})}
function acomp(d){let c=head();c.push(P({alignment:AlignmentType.CENTER,children:[R({text:"DECLARAÇÃO DE ACOMPANHANTE",bold:true})]}),P({text:""}),P({children:[R({text:"Declaro para fins de comprovação junto ao empregador..."})]}));return new Document({sections:[{children:c}]})}
function cell(d,via,special=false){let c=[P({children:[new ImageRun({data:LOGO,transformation:{width:special?45:42,height:special?60:56},type:"jpg"})]})];if(special){c.push(P({children:[R({text:"HOSPITAL ALTA VIDA",bold:true,size:14})]}),P({children:[R({text:`${via}`,bold:true})]}))};return new TableCell({children:c})}
function receita(d,special=false){let t=new Table({width:{size:100,type:WidthType.PERCENTAGE},columnWidths:[7920,7920],rows:[new TableRow({children:[cell(d,"1ª via",special),cell(d,"2ª via",special)]})]});return new Document({sections:[{children:[t]}]})}
function valid(p){if(!p||!String(p.paciente||"").trim())return"Paciente sem nome";if(p.atestado){let a=p.atestado;if(!a.procedimento||!a.cid10||!a.dataProcedimento||!a.dataInternacao||!a.diasAfastamento)return"Atestado incompleto"};return null}
async function makeZip(x){let z=new JSZip();for(const p of x.pacientes){let b={paciente:p.paciente,hoje:x.hoje},s=safe(p.paciente);if(p.atestado)z.file(`Atestado_${s}.docx`,await Packer.toBuffer(atestado({...b,...p.atestado})));if(p.acomp)z.file(`Acomp_${s}.docx`,await Packer.toBuffer(acomp(b)));if(p.receita)z.file(`Receita_${s}.docx`,await Packer.toBuffer(receita(b,p.receita.special)))};return await z.generateAsync({type:"nodebuffer"})}
function tos(m){let a=process.env.PERSONAL_EMAIL,b=process.env.SERVICE_EMAIL;if(m==="personal")return a?[a]:[];if(m==="service")return b?[b]:[];if(m==="both")return[...new Set([a,b].filter(Boolean))]}
module.exports=async(req,res)=>{res.setHeader("Cache-Control","no-store");if(req.method!=="POST")return res.status(405).json({ok:false,error:"Método não permitido"});try{if(!process.env.APP_KEY||req.headers["x-api-key"]!==process.env.APP_KEY)return res.status(401).json({ok:false,error:"Não autorizado"});let{pacientes:x,hoje:i}=req.body;if(!Array.isArray(x)||!i)return res.status(400).json({ok:false,error:"Dados inválidos"});for(let p of x){let e=valid(p);if(e)return res.status(400).json({ok:false,error:e})};let b=await makeZip({pacientes:x,hoje:i});res.setHeader("Content-Type","application/zip");res.setHeader("Content-Disposition","attachment; filename=documentos.zip");res.send(b)}catch(e){console.error(e);res.status(500).json({ok:false,error:"Erro ao gerar documentos"})}};
